#!/usr/bin/perl

use lib '/usr/share/openqa/lib';
use Capture::Tiny qw(capture);
use Mojo::JSON qw(decode_json encode_json);
use OpenQA::CLI;
use strict;
use warnings;

my @group_ids = qw();

foreach my $group (@group_ids) {
    my $api  = OpenQA::CLI->new() or die "Cannot instance OpenQA::CLI\n";
    my @api_common = qw(api --osd -X);
    my ($stdout, $stderr, $retval) = capture { $api->run(@api_common, 'GET', '--pretty', "job_groups/$group") };
    my $json = decode_json($stdout);
    my $data = { name => $json->[0]->{name}, description => $json->[0]->{description} };
    if ($data->{description} =~ /QE-SAP/) {
        $data->{description} = 'New Description';
        print "Group name:[$data->{name}],id:$group is a QE-SAP job group. It will be updated\n";
        $api->run(@api_common, 'PUT', '--form', '--data', encode_json($data), "job_groups/$group");
    }
    else {
        print "Group name:[$data->{name}],id:$group is not an exclusive QE-SAP job group. Skipping.\n";
    }
}

