FROM openqa

RUN zypper in -y make ruby ruby2.1-rubygem-sass perl-Pod-POM && zypper clean

EXPOSE 80

#ENV PERL_MM_USE_DEFAULT 1
#ENV PERL_EXTUTILS_AUTOINSTALL "--defaultdeps"
#
#RUN perl -MCPAN -e "install Pod::Tree"

ENTRYPOINT ["/root/run_openqa.sh"]
